# Generated by Django 6.0.5 on 2026-06-02 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grinder", "0006_question_difficulty_alter_userdomainelo_elo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomainelo",
            name="competence",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userdomainelo",
            name="elo",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
    ]
